swagger: "2.0"
info:
  version: "0.3.2"
  title: Integração SugarCRM - Mobly
host: tbd
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: customer
    description: Requisições que retornam informações do cliente Mobly
paths:
  /customerCart/{customerID}:
    get:
      tags:
        - customer
      description: Retorna os itens do carrinho do cliente que foi passado o ID.
      operationId: getCustomerCart
      parameters:
        - name : customerID
          in: path
          description: ID do consumidor
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/cartResponse"
  /customerRecommendation/{customerID}:
    get:
      tags:
        - customer
      description: Retorna um item recomendado para a compra de um cliente
      operationId: getCustomerRecommendation
      parameters:
        - name: customerID
          in: path
          description: ID do consumidor
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/itemRecommended"
  /customerMetrics/{customerID}:
    get:
      tags:
        - customer
      description: Retorna os indicadores do cliente, as métricas que são enviadas dentro do array podem ter campos adicionados de acordo com a necessidade.Importante anotar que a melhor prática é deixar os campos retornados marcados como não obrigatório do lado do Sugar para manter a flexibilidade de se trabalhar com quaisqer pares de  chaves/valores que forem enviados
      operationId: getCustomerMetrics
      parameters:
        - name: customerID
          in: path
          description: ID do consumidor
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/customerMetrics"
        404:
          description: Cliente não encontrado
definitions:
  cartResponse:
    type: object
    properties:
      cart_id:
        type: string
      cart_date:
        type: string
        format: date
      cart_itens:
        type: array
        maxLength: 5
        minLength: 0
        items:
          $ref: "#/definitions/cart_itens"
  cart_itens:
    type: object
    properties:
      cart_item_sku:
        type: string
      cart_item_sku_description:
        type: string
      cart_item_sku_color:
        type: string
      cart_item_sku_prev_delivery:
        type: string
        format: date
      cart_item_sku_price:
        type: number
        format: float
      cart_item_sku_img:
        type: string
  itemRecommended:
    type: object
    properties:
      item_name:
        type: string
      item_sku:
        type: string
      item_img:
        type: string
        description: URL do thumbnail do item
      item_factor:
        type: number
        format: float
        description: Porcentagem de eventual compra
  customerMetrics:
    type: object
    properties:
      cst_mtrc_dashlet_name:
        type: string
        description: Indica qual dashlet deve renderizar as informações
      cst_mtrc_type:
          type: string
          description: tbd
      cst_mtrc_timestamp:
          type: string
          format: date-time
      cst_mtrc_customer_id:
        type: string
        description: Código identificador do cliente
      cst_mtrc_customerMetrics:
        type: array
        description: Métricas enviadas
        minLength: 0
        maxLength: 10
        items:
          $ref: "#/definitions/cst_mtrc_customerMetrics"
  cst_mtrc_customerMetrics:
    type: object
    description: Lista de indicadores por dashlet
    properties:
      customerMetric_label:
        description: Nome do campo
        type: string
      customerMetric_info:
        description: tbd
        type: string
      customerMetric_value:
        description: Valor
        type: number
        format: float
      customerMetric_total:
        description: Valor total
        type: number
        format: float