swagger: "2.0"
info:
  version: "0.4.4"
  title: Integração SugarCRM - Mobly
  description: 0.4.4 fix em customerMetrics, customerCart alterado para apenas um carrinho
host: tbd
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: customer
    description: Requisições que retornam informações do cliente Mobly
  - name: processes
    description: Requisições que retornam informações de processos
paths:
  /customerCart/{customerID}:
    get:
      tags:
        - customer
      summary: Consulta de carrinhos
      description: Retorna os itens do carrinho do cliente que foi passado o ID.
      operationId: getCustomerCart
      parameters:
        - name : customerID
          in: path
          description: ID do consumidor
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/cartResponse"
        400:
          description: Error
          schema:
            $ref: "#/definitions/stdErroMessage"
  /customerRecommendation/{customerID}:
    get:
      tags:
        - customer
      summary: Consulta de recomendação
      description: Retorna um item recomendado para a compra de um cliente
      operationId: getCustomerRecommendation
      parameters:
        - name: customerID
          in: path
          description: ID do consumidor
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/itemRecommended"
        400:
          description: Error
          schema:
            $ref: "#/definitions/stdErroMessage"
  /customerMetrics/{customerID}:
    get:
      tags:
        - customer
      summary: Consulta de métricas
      description: Retorna os indicadores do cliente, as métricas que são enviadas dentro do array podem ter campos adicionados de acordo com a necessidade.Importante anotar que a melhor prática é deixar os campos retornados marcados como não obrigatório do lado do Sugar para manter a flexibilidade de se trabalhar com quaisqer pares de  chaves/valores que forem enviados
      operationId: getCustomerMetrics
      parameters:
        - name: customerID
          in: path
          description: ID do consumidor
          required: true
          type: string
        - name: dashletName
          in: query
          description: Identificador da dashlet que está dando request
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/customerMetrics"
        400:
          description: Cliente não encontrado
          schema:
            $ref: "#/definitions/stdErroMessage"
  /itemEvaluation:
    get:
      tags: 
        - processes
      summary: Consulta de valor de rebate
      description: Envia para o INO os itens que precisam de avaliação para solicitar o rebate, o INO retorna o valor máximo do rebate que pode ser oferecido
      operationId: getItemEvaluation
      parameters:
        - name: item_evaluted
          in: body
          description: Objeto com os itens que devem ser avaliados
          required: true
          schema:
            $ref: "#/definitions/item_evaluated"
      responses:
        200:
          description: Sucess
          schema:
            $ref: "#/definitions/item_evaluated_value"
        400:
          description: Error
          schema:
            $ref: "#/definitions/stdErroMessage"
  /rebateValueApproval:
    post:
      tags:
        - processes
      summary: Pedido de aprovação/registro no INO de rebate
      description: Envia para o INO o valor do rebate escolhido pelo atendente e aguarda a confirmação por parte do INO
      operationId: postRebateValueApproval
      parameters:
        - name: rebate_value
          in: body
          description: Objeto com os items do rebate e o valor do rebate acordado com o cliente
          required: true
          schema:
            $ref: "#/definitions/rebate_value"
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/rebate_value_confirmation"
        400:
          description: Error
          schema:
            $ref: "#/definitions/stdErroMessage"
  # /valueRebate/{rebate_itens}:
  #   get:
  #     tags:
  #       - processes
  #     description: Retorna o valor do rebate possível de se oferecer
  #     operationId: getValueRebate
  #     parameters:
  #         - name: rebate_itens
  #           in: path
  #           description: Itens que vão ser considerados no cálculo do rebate
  #           required: true
  #           type: array
  #           items:
  #             name:
  #               type: string
  #     responses:
  #       200:
  #         description: OK
definitions:
  stdErroMessage:
    description: Mensagem de erro a ser usada nas integrações
    type: object
    properties:
      response_status:
        type: string
        description: Indica o código do erro, podemos convencionar a usar os códigos HTTP 400/500 para generalizar
        enum:
          - 400
          - 500
      request_id:
        type: string
        description: Enviar nesse campo o ID da requisição, por exemplo, se for consulta de pedido enviar o ID do pedido, se for de cliente enviar o do cliente, etc
      message:
        type: string
        description: Nesse campo será descrito o erro que aconteceu
  cartResponse:
    type: object
    properties:
      cart_id:
        type: string
      cart_date:
        type: string
        format: date
      cart_itens:
        type: array
        maxLength: 5
        minLength: 0
        items:
          $ref: "#/definitions/cart_itens"
  cart_itens:
    type: object
    properties:
      cart_item_sku:
        type: string
      cart_item_sku_description:
        type: string
      cart_item_sku_color:
        type: string
      cart_item_sku_prev_delivery:
        type: string
        format: date
      cart_item_sku_price:
        type: number
        format: float
      cart_item_sku_img:
        type: string
  itemRecommended:
    type: object
    properties:
      item_name:
        type: string
      item_sku:
        type: string
      item_img:
        type: string
        description: URL do thumbnail do item
      item_factor:
        type: number
        format: float
        description: Porcentagem de eventual compra
  customerMetrics:
    type: object
    properties:
      cst_mtrc_timestamp:
          type: string
          format: date-time
      cst_mtrc_customer_id:
        type: string
        description: Código identificador do cliente
      cst_mtrc_customerMetrics:
        type: array
        description: Métricas enviadas
        minLength: 0
        maxLength: 10
        items:
          $ref: "#/definitions/cst_mtrc_customerMetrics"
  cst_mtrc_customerMetrics:
    type: object
    description: Lista de indicadores por dashlet
    properties:
      cst_mtrc_type:
        type: string
        description: Indica qual o formato que as informações serão renderizadas
      customerMetric_label:
        description: Nome do campo
        type: string
      customerMetric_info:
        description: tbd
        type: string
      customerMetric_value:
        description: Valor
        type: number
        format: float
      customerMetric_total:
        description: Valor total
        type: number
        format: float
  item_evaluated:
    type: object
    description: Itens enviados para o INO para obter a avaliação do rebate
    properties:
      order_id:
        description: ID do pedido
        type: string
      order_items:
        description: Items que são enviados para o INO para serem avaliados
        type: array
        items:
          $ref: "#/definitions/order_items"
  order_items:
    type: object
    description: Items que são enviados para o INO para serem avaliados
    properties:
      order_items_id:
        description: ID do item
        type: string
      order_items_status:
        type: string
        description: Status de cada item 
        enum:
          - Entregue
          - Outros
      order_items_evaluation:
        type: string
        description: Avaliação do item, depende do que for passado no status
        enum:
          - 
          - Avaria
          - Sucata
          - Perfeito Estado
  item_evaluated_value:
    type: object
    description: Retorno do INO com o valor total do rebate
    properties:
      order_id:
        description: ID do pedido
        type: string
      item_evaluated_value_total:
        description: Valor total do rebate
        type: number
        format: float
      iev_order_items:
        description: Lista dos items que foram avaliados
        type: array
        items:
          $ref: "#/definitions/resp_order_items"
  resp_order_items:
    type: object
    description: Lista dos items que foram avaliados
    properties:
      resp_order_items_id:
        description: ID do item
        type: string
      resp_order_items_status:
        description: Status do item, é retornado porque pode ser diferente no INO, preciso pensar como esse valor será armazaenado no sistema, já que foi decidido que teriamos no case a imagem chapada do pedido e seus itens no case/Sugar
        type: string
  rebate_value:
    type: object
    description: Objeto com os items do rebate e o valor do rebate acordado com o cliente
    properties:
      order_id: 
        description: ID do pedido
        type: string
      sugar_crm_user_login:
        description: Login do usuário que está pedindo o rebate
        type: string
      rebate_value_total: 
        description: Valor do rebate
        type: number
        format: float
      rebate_value_order_items:
        type: array
        items:
          $ref: "#/definitions/resp_order_items"
  rebate_value_confirmation:
    type: object
    description: Confirmação do INO que o rebate foi registrado
    properties:
      response_status:
        description: Código HTTP de resposta
        type: string
      order_id:
        description: ID do pedido
        type: string
      message:
        description: Mensagem de confirmação
        type: string

